vim.opt.runtimepath:append("~/nvim-treesitter/parsers")

require("nvim-treesitter.configs").setup({
  parser_intsall_dir = "~/nvim-treesitter/parsers",

  ensure_installed = {
    "awk",
    "c",
    "cmake",
    "cpp",
    "css",
    "csv",
    "diff",
    "editorconfig",
    "eex",
    "elixir",
    "embedded_template",
    "erlang",
    "gdscript",
    "gdshader",
    "gitattributes",
    "go",
    "godot_resource",
    "html",
    "java",
    "javascript",
    "jq",
    "jsdoc",
    "json",
    "llvm",
    "lua",
    "luadoc",
    "markdown",
    "objdump",
    "prisma",
    "python",
    "query",
    "regex",
    "ruby",
    "rust",
    "scala",
    "sql",
    "toml",
    "tsx",
    "typescript",
    "vim",
    "vimdoc",
    "vue",
    "xml",
    "yaml",
  },

  sync_install = false,

  auto_install = true,

  ignore_install = {},

  highlight = {
    enable = true,
    additional_vim_regex_highlighting = false,
  },
})
